//
// This file was generated by the Eclipse Implementation of JAXB, v2.3.7 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.15 at 10:52:12 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.com/soapproducing/soapdemo/entity", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bt.ms.im.clients.products.entity;
