<?xml version="1.0" encoding="UTF-8"?>
<!--
    $Id: //Source_Code/BCC/Dise3G/7.3/8/WebService/Schema/wsdl/corporate/corporateservice.wsdl#1 $
    $Header: //Source_Code/BCC/Dise3G/7.3/8/WebService/Schema/wsdl/corporate/corporateservice.wsdl#1 $
    $DateTime: 2008/01/06 10:20:44 $
    $Author: Malgorzata.Grzybowska $
    $File: //Source_Code/BCC/Dise3G/7.3/8/WebService/Schema/wsdl/corporate/corporateservice.wsdl $
    $Revision: #1 $
    (c) Copyright 2008 Martin Dawes Systems Ltd
-->
<definitions targetNamespace="http://mdsuk.com/ws/dise3g/corporate/service"
    xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:target="http://mdsuk.com/ws/dise3g/corporate/service"
    xmlns:definition="http://mdsuk.com/ws/dise3g/corporate/definition"
    xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/">

    <import namespace="http://mdsuk.com/ws/dise3g/corporate/definition" location="corporate.wsdl"/>

    <!-- binding declns -->
    <binding name="CorporateSoapBinding" type="definition:CorporatePortType">
        <documentation>
            This Webservice binding encompasses all operations relating to Corporate management.
        </documentation>
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="CreateCorporate">
            <documentation>Creates a Corporate</documentation>
			<soap:operation/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="SystemFault">
                <soap:fault name="SystemFault" use="literal"/>
            </fault>
            <fault name="SecurityFault">
                <soap:fault name="SecurityFault" use="literal"/>
            </fault>
            <fault name="ValidationFault">
                <soap:fault name="ValidationFault" use="literal"/>
            </fault>
            <fault name="ServiceUnavailableFault">
                <soap:fault name="ServiceUnavailableFault" use="literal"/>
            </fault>
        </operation>
        <operation name="UpdateCorporate">
            <documentation>Updates a Corporate</documentation>
			<soap:operation/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="SystemFault">
                <soap:fault name="SystemFault" use="literal"/>
            </fault>
            <fault name="SecurityFault">
                <soap:fault name="SecurityFault" use="literal"/>
            </fault>
            <fault name="ValidationFault">
                <soap:fault name="ValidationFault" use="literal"/>
            </fault>
            <fault name="ServiceUnavailableFault">
                <soap:fault name="ServiceUnavailableFault" use="literal"/>
            </fault>
        </operation>
        <operation name="QueryCorporate">
            <documentation>Corporate retrieval</documentation>
			<soap:operation/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="SystemFault">
                <soap:fault name="SystemFault" use="literal"/>
            </fault>
            <fault name="SecurityFault">
                <soap:fault name="SecurityFault" use="literal"/>
            </fault>
            <fault name="ValidationFault">
                <soap:fault name="ValidationFault" use="literal"/>
            </fault>
            <fault name="ServiceUnavailableFault">
                <soap:fault name="ServiceUnavailableFault" use="literal"/>
            </fault>
        </operation>
    </binding>

    <!-- service declns -->
    <service name="CorporatePort">
        <documentation>This is the webservice for DISE corporate processing.</documentation>
        <port name="CorporatePort" binding="target:CorporateSoapBinding">
            <soap:address location="http://localhost:9082/axis/services/CorporatePort"/>
        </port>
    </service>
</definitions>
