<?xml version="1.0" encoding="UTF-8"?>
<!-- 
    $Id: //Source_Code/BCC/Dise3G/7.3/8/WebService/Schema/wsdl/oam/oamservice.wsdl#1 $
    $Header: //Source_Code/BCC/Dise3G/7.3/8/WebService/Schema/wsdl/oam/oamservice.wsdl#1 $
    $DateTime: 2021/03/22 14:14:36 $
    $Author: BuildMaster $
    $File: //Source_Code/BCC/Dise3G/7.3/8/WebService/Schema/wsdl/oam/oamservice.wsdl $
    $Revision: #1 $
    (c) Copyright 2007 Martin Dawes Systems Ltd
-->
<definitions targetNamespace="http://mdsuk.com/ws/dise3g/oam/service"
    xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:definition="http://mdsuk.com/ws/dise3g/oam/definition"
    xmlns:target="http://mdsuk.com/ws/dise3g/oam/service">

    <import namespace="http://mdsuk.com/ws/dise3g/oam/definition" location="oam.wsdl"/>

    <!-- binding declns -->
    <binding name="OAMSOAPBinding" type="definition:OAMPortType">
        <documentation> This Webservice binding encompasses all operations relating to Dise3G OAM
            WebServices. </documentation>

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProvisionOAMAccess">
            <documentation> Provisions a Dise3G Account for OAM access. </documentation>
			<soap:operation/>
            <input>
                <soap:body use="literal"/>
            </input>
            <output>
                <soap:body use="literal"/>
            </output>
            <fault name="SystemFault">
                <soap:fault use="literal" name="SystemFault"/>
            </fault>
            <fault name="SecurityFault">
                <soap:fault use="literal" name="SecurityFault"/>
            </fault>
            <fault name="ValidationFault">
                <soap:fault use="literal" name="ValidationFault"/>
            </fault>
            <fault name="ServiceUnavailableFault">
                <soap:fault use="literal" name="ServiceUnavailableFault"/>
            </fault>
        </operation>
    </binding>

    <!-- service declns -->
    <service name="OAMPort">
        <documentation> This is the WebService for Dise3G OAM management. </documentation>
        <port name="OAMPort" binding="target:OAMSOAPBinding">
            <soap:address location="http://localhost:8080/axis/services/OAMService"/>
        </port>
    </service>

</definitions>
