<?xml version="1.0" encoding="UTF-8"?>
<definitions targetNamespace="http://mdsuk.com/ws/dise3g/fault/definition"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:target="http://mdsuk.com/ws/dise3g/fault/definition">

    <documentation>This Webservice definition encompasses all operations relating to Faults. </documentation>

    <types>
        <schema xmlns="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://mdsuk.com/ws/dise3g/fault/definition"
            xmlns:fault="http://mdsuk.com/ws/dise3g/fault"
            elementFormDefault="qualified">
            <import namespace="http://mdsuk.com/ws/dise3g/fault"
                schemaLocation="../../xsd/faults.xsd"/>

            <element name="SystemFault" type="fault:SystemFault"/>
            <element name="SecurityFault" type="fault:SecurityFault"/>
            <element name="ValidationFault" type="fault:ValidationFault"/>
            <element name="ServiceUnavailableFault" type="fault:ServiceUnavailableFault"/>

        </schema>
    </types>
  
    <message name="SystemFault">
        <part name="SystemFault" element="target:SystemFault"/>
    </message>

    <message name="SecurityFault">
        <part name="SecurityFault" element="target:SecurityFault"/>
    </message>

    <message name="ValidationFault">
        <part name="ValidationFault" element="target:ValidationFault"/>
    </message>

    <message name="ServiceUnavailableFault">
        <part name="ServiceUnavailableFault" element="target:ServiceUnavailableFault"/>
    </message>

</definitions>

